backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "site.json"
        label: "Contacts"
        name: "contacts"
        format: "json"
        fields:
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
