backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "site_en"
        label: "Site Text (EN)"
        file: "data/site_en.json"
        format: "json"
        fields:
          - {label: "Brand", name: "brand", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
      - name: "site_it"
        label: "Site Text (IT)"
        file: "data/site_it.json"
        format: "json"
        fields:
          - {label: "Brand", name: "brand", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
      - name: "site_ru"
        label: "Site Text (RU)"
        file: "data/site_ru.json"
        format: "json"
        fields:
          - {label: "Brand", name: "brand", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}

  - name: "catalog"
    label: "Catalog"
    files:
      - name: "products"
        label: "Products"
        file: "data/products.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "number"}
              - {label: "Currency", name: "currency", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Color", name: "color", widget: "string"}
              - {label: "Stock", name: "stock", widget: "select", options: ["in_stock", "limited", "out_of_stock"]}
              - {label: "Description", name: "description", widget: "text"}

  - name: "reviews"
    label: "Reviews"
    files:
      - name: "reviews"
        label: "Reviews"
        file: "data/reviews.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
