backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "site"
        label: "Contacts (site.json)"
        file: "site.json"
        format: "json"
        fields:
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
